default:
  env:
    - name: OTEL_COLLECTOR_NAME
      value: collector-collector.observability.svc.cluster.local

opentelemetry-collector:
  enabled: false

jaeger:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false

opensearch:
  enabled: false
